# Generated by Django 6.0.3 on 2026-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("numero_semestres", models.PositiveIntegerField()),
                ("ects_total", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("objetivo", models.TextField()),
                ("url_website", models.URLField()),
                ("saidas_profissionais", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="licenciaturas/"
                    ),
                ),
            ],
        ),
    ]
