# Generated by Django 6.0.3 on 2026-04-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaInteresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("categoria", models.CharField(max_length=100)),
                ("destaque", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("nivel", models.CharField(max_length=100)),
                ("evidencia", models.TextField()),
                ("destaque", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("numero_semestres", models.PositiveIntegerField()),
                ("ects_total", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("objetivo", models.TextField()),
                ("url_website", models.URLField()),
                ("saidas_profissionais", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="licenciaturas/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("url_website", models.URLField()),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("descricao", models.TextField()),
                ("certificado_url", models.URLField(blank=True, null=True)),
                ("estado", models.CharField(max_length=100)),
                ("ordem_cronologica", models.IntegerField()),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("ano_realizacao", models.PositiveIntegerField()),
                ("estado", models.CharField(max_length=100)),
                ("destaque", models.BooleanField(default=False)),
                (
                    "area_interesse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.areainteresse",
                    ),
                ),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=200)),
                ("orientador", models.CharField(max_length=200)),
                ("curso", models.CharField(max_length=200)),
                ("ano", models.PositiveIntegerField()),
                ("resumo", models.TextField()),
                ("palavras_chave", models.TextField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="tfcs/")),
                ("email_autor", models.EmailField(max_length=254)),
                ("documento_url", models.URLField()),
                ("classificacao_interesse", models.CharField(max_length=100)),
                ("destaque", models.BooleanField(default=False)),
                (
                    "area_interesse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.areainteresse",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_registo", models.DateField()),
                ("versao_modelo", models.CharField(max_length=100)),
                ("decisoes_tomadas", models.TextField()),
                ("erros_encontrados", models.TextField()),
                ("correcoes_realizadas", models.TextField()),
                ("justificacao_modelacao", models.TextField()),
                ("uso_ia", models.TextField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "competencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makingofs",
                        to="portfolio.competencia",
                    ),
                ),
                (
                    "formacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makingofs",
                        to="portfolio.formacao",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makingofs",
                        to="portfolio.projeto",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makingofs",
                        to="portfolio.tecnologia",
                    ),
                ),
                (
                    "tfc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makingofs",
                        to="portfolio.tfc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano_curricular", models.PositiveIntegerField()),
                ("semestre", models.PositiveIntegerField()),
                ("ects", models.PositiveIntegerField()),
                ("apresentacao", models.TextField()),
                ("programa", models.TextField()),
                ("objectivos", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="unidades_curriculares/"
                    ),
                ),
                ("url_website", models.URLField()),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("ficheiro", models.FileField(upload_to="midia/")),
                ("tipo", models.CharField(max_length=100)),
                ("legenda", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("data_upload", models.DateField()),
                (
                    "making_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midias",
                        to="portfolio.makingof",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midias",
                        to="portfolio.projeto",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midias",
                        to="portfolio.tecnologia",
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midias",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="makingof",
            name="unidade_curricular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="makingofs",
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("pagina_pessoal_url", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("area_especializacao", models.CharField(max_length=200)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
                (
                    "unidades_curriculares",
                    models.ManyToManyField(
                        blank=True,
                        related_name="docentes",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
