# Generated by Django 6.0.3 on 2026-04-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano_curricular", models.PositiveIntegerField()),
                ("semestre", models.PositiveIntegerField()),
                ("ects", models.PositiveIntegerField()),
                ("apresentacao", models.TextField()),
                ("programa", models.TextField()),
                ("objectivos", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="unidades_curriculares/"
                    ),
                ),
                ("url_website", models.URLField()),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
