# Generated by Django 6.0.3 on 2026-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("pagina_pessoal_url", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("area_especializacao", models.CharField(max_length=200)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
                (
                    "unidades_curriculares",
                    models.ManyToManyField(
                        blank=True,
                        related_name="docentes",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
