# Generated by Django 6.0.3 on 2026-04-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("url_website", models.URLField()),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
